#### Python Pandas
- pandas is python library used for working on data sets like Excel sheet or spread sheet and csv(comma seperated values) 
- pandas is mainly used to anlyzing data,cleaning data, exploring data and manipulating data.
- pip install pandas 
- import pandas
- import pandas as pd

In [1]:
import pandas
print(dir(pandas))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__deprecated_num_index_names', '__dir__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_is_numpy_dev', '_libs', '_testing', '_typing', '_version', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'concat', 'core', 'crosstab', 'cut', 'date_range', 'describe_option', 'errors', 'eval', 'factorize', 'get_dummies', 'get_option', 'infer_freq', 'interval_range', 'io', 'isna', 'isnull', 'json_normalize', 'lreshape', 'melt', 'merge', 'merge_asof', 'merge_ordered', 'notna', 'notnull', 'offsets', 'option_context', 'options', 'pandas', 'period_range', 'pivot', 'pivot_table', 'plotting', 'qcut', 'read_clipboard', 'read_csv', 'read_excel', 'read_feather', 'read_fwf', 'read_gbq', 'read_hdf', 'read_html', 'read_json', 'read_orc', 'read_parquet', 'read_pickle', 'read_sas', 'read_spss', 'read_sql', 'read_sql_query', 'read_sql_table', 'read_stata', 'read_table', 'read_xml', 'reset_option', 'set_eng_float_format', 'set_option', 'show_versions', 'test', 'testing', 'timedelta_range', 'to_datetime', 'to_numeric', 'to_pickle', 'to_timedelta', 'tseries', 'unique', 'util', 'value_counts', 'wide_to_long']

In [3]:
df2=pandas.read_json('info.json')
df2

ValueError: Expected object or value

In [2]:
df=pandas.read_json("data.json")
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [2]:
import pandas as pd
data = {'names':['venkatesh','aniket','joseph','indu','sonam','tanzeela','bhavya'],
       'address':['hyderabad','mumbai','kolkata','pune','delhi','chennai','banglore'],
       'id':[1211,1212,1214,1213,1215,1218,1217],
       'salary':[10000,20000,30000,40000,50000,60000,70000]}
# data set is nothing but rows columns data
output = pd.DataFrame(data)
output

       names    address    id  salary
0  venkatesh  hyderabad  1211   10000
1     aniket     mumbai  1212   20000
2     joseph    kolkata  1214   30000
3       indu       pune  1213   40000
4      sonam      delhi  1215   50000
5   tanzeela    chennai  1218   60000
6     bhavya   banglore  1217   70000

In [3]:
import pandas as pd
data1 = {'names':['venkatesh','aniket','joseph','indu','sonam','tanzeela','bhavya'],
       'address':['hyderabad','mumbai','kolkata','pune','delhi','chennai','banglore'],
       'sid':[1211,1212,1214,1213,1215,1218,1217],
       'gender':['M','M','M','F','F','F','F'],
       'contact':[98765,67899,76543,875643,2345666,675466,987655],
       'branch':['ECE','CSE','IT','CSE','EEE','ECE','CSE']}
# data set is nothing but rows columns data
output = pd.DataFrame(data1)
output

       names    address   sid gender  contact branch
0  venkatesh  hyderabad  1211      M    98765    ECE
1     aniket     mumbai  1212      M    67899    CSE
2     joseph    kolkata  1214      M    76543     IT
3       indu       pune  1213      F   875643    CSE
4      sonam      delhi  1215      F  2345666    EEE
5   tanzeela    chennai  1218      F   675466    ECE
6     bhavya   banglore  1217      F   987655    CSE

In [6]:
import pandas as pd
print(pd.__version__)

1.4.4

In [10]:
# series data
# a pandas 
# 1-d data we can call it as a series
result1 = pd.Series([2,4,6,8,10,12,14,16])
print(result1)
# in output default indexs are start from 0 to n

0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    16
dtype: int64

In [14]:
result2 = pd.Series(['venkatesh','aniket','joseph','indu','sonam','tanzeela','bhavya'],
                   index=['name1','name2','name3','name4','name5','name6','name7'])
print(result2['name3'])
print(result2['name6'])

joseph
tanzeela

In [18]:
import pandas as pd
data = {'names':['venkatesh','aniket','joseph','indu','sonam','tanzeela','bhavya'],
       'address':['hyderabad','mumbai','kolkata','pune','delhi','chennai','banglore'],
       'id':[1211,1212,1214,1213,1215,1218,1217],
       'salary':[10000,20000,30000,40000,50000,60000,70000]}
# data set is nothing but rows columns data
output = pd.DataFrame(data,index=['r1','r2','r3','r4','r5','r6','r7'])
output

        names    address    id  salary
r1  venkatesh  hyderabad  1211   10000
r2     aniket     mumbai  1212   20000
r3     joseph    kolkata  1214   30000
r4       indu       pune  1213   40000
r5      sonam      delhi  1215   50000
r6   tanzeela    chennai  1218   60000
r7     bhavya   banglore  1217   70000

In [19]:
# dataframes - pandas dataframes is a 2-D data structure
# 1. dictionaries
# 2. csv data
# 3. excel sheet or spread sheet
# 4. json type of data

In [23]:
import numpy
from numpy import random
result = random.randint(100,size=(5))
result

array([ 8, 63, 51, 25, 96])

In [25]:
import pandas as pd
import numpy as np
from numpy import random
info = {'names':['venkat','aniket','joseph','indu','sonam','tanzeela','bhavya','divya','bharath'],
       'Mathematics':random.randint(100,size=(9)),
       'Python':random.randint(100,size=(9)),
       'Java':random.randint(100,size=(9)),
       'DS':random.randint(100,size=(9)),
       'ML':random.randint(100,size=(9)),
       'AI':random.randint(100,size=(9)),
       'Physics':random.randint(100,size=(9)),
       'Chemistry':random.randint(100,size=(9)),
       'English':random.randint(100,size=(9))}
data = pd.DataFrame(info)
print(data.head()) # head function return top 5 record

    names  Mathematics  Python  Java  DS  ML  AI  Physics  Chemistry  English
0  venkat           65      63    71  26  85  91       16         59       70
1  aniket           98      97    51  47  93  12       43         32       63
2  joseph           35      94    17  23  53  41       35         85       20
3    indu            9      95    16  83  62  65       28         60       21
4   sonam           42      28    33  26  29  83       41         97       10

In [26]:
print(data.tail()) # tail function last 5 records

      names  Mathematics  Python  Java  DS  ML  AI  Physics  Chemistry  \
4     sonam           42      28    33  26  29  83       41         97
5  tanzeela           72      99    69  48  36  82       74         22
6    bhavya           26      46    68  88  31  50       19         15
7     divya            7       6    58  78  95  13       94         40
8   bharath           62       7    65  43  60  80       68         24

   English
4       10
5       28
6       31
7       79
8       52